[package]
name = "rustyraytracer"
version = "0.1.0"
authors = ["jonathan <thaler.jonathan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.15.0"
glm = "0.2.3"